/* tslint:disable */
/* eslint-disable */
/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAccountCommand
 */
export interface CreateAccountCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateAccountCommand
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAccountCommand
     */
    password: string;
}

/**
 * Check if a given object implements the CreateAccountCommand interface.
 */
export function instanceOfCreateAccountCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userName" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function CreateAccountCommandFromJSON(json: any): CreateAccountCommand {
    return CreateAccountCommandFromJSONTyped(json, false);
}

export function CreateAccountCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccountCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userName': json['userName'],
        'password': json['password'],
    };
}

export function CreateAccountCommandToJSON(value?: CreateAccountCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userName': value.userName,
        'password': value.password,
    };
}

