/* tslint:disable */
/* eslint-disable */
/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEnvironmentVariableDto
 */
export interface UpdateEnvironmentVariableDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateEnvironmentVariableDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEnvironmentVariableDto
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEnvironmentVariableDto
     */
    value: string;
}

/**
 * Check if a given object implements the UpdateEnvironmentVariableDto interface.
 */
export function instanceOfUpdateEnvironmentVariableDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function UpdateEnvironmentVariableDtoFromJSON(json: any): UpdateEnvironmentVariableDto {
    return UpdateEnvironmentVariableDtoFromJSONTyped(json, false);
}

export function UpdateEnvironmentVariableDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEnvironmentVariableDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'key': json['key'],
        'value': json['value'],
    };
}

export function UpdateEnvironmentVariableDtoToJSON(value?: UpdateEnvironmentVariableDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'key': value.key,
        'value': value.value,
    };
}

