/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import App from './model/App';
import AppDto from './model/AppDto';
import AppsVm from './model/AppsVm';
import Certificate from './model/Certificate';
import CertificateDto from './model/CertificateDto';
import CertificatesVm from './model/CertificatesVm';
import Channel from './model/Channel';
import ChannelDto from './model/ChannelDto';
import ChannelRevisionSelectionStrategy from './model/ChannelRevisionSelectionStrategy';
import ChannelsVm from './model/ChannelsVm';
import CreateAccountCommand from './model/CreateAccountCommand';
import CreateAppCommand from './model/CreateAppCommand';
import CreateCertificateCommand from './model/CreateCertificateCommand';
import CreateChannelCommand from './model/CreateChannelCommand';
import CreateEnvironmentVariableCommand from './model/CreateEnvironmentVariableCommand';
import CreateTokenCommand from './model/CreateTokenCommand';
import DomainEvent from './model/DomainEvent';
import EnvironmentVariable from './model/EnvironmentVariable';
import EnvironmentVariableDto from './model/EnvironmentVariableDto';
import EnvironmentVariablesVm from './model/EnvironmentVariablesVm';
import RegisterRevisionCommand from './model/RegisterRevisionCommand';
import Revision from './model/Revision';
import RevisionDto from './model/RevisionDto';
import RevisionsVm from './model/RevisionsVm';
import TokenInfo from './model/TokenInfo';
import AccountApi from './api/AccountApi';
import AppApi from './api/AppApi';
import CertificateApi from './api/CertificateApi';
import ChannelApi from './api/ChannelApi';
import EnvironmentVariableApi from './api/EnvironmentVariableApi';
import RevisionApi from './api/RevisionApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var HippoWeb = require('index'); // See note below*.
* var xxxSvc = new HippoWeb.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new HippoWeb.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new HippoWeb.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new HippoWeb.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The App model constructor.
     * @property {module:model/App}
     */
    App,

    /**
     * The AppDto model constructor.
     * @property {module:model/AppDto}
     */
    AppDto,

    /**
     * The AppsVm model constructor.
     * @property {module:model/AppsVm}
     */
    AppsVm,

    /**
     * The Certificate model constructor.
     * @property {module:model/Certificate}
     */
    Certificate,

    /**
     * The CertificateDto model constructor.
     * @property {module:model/CertificateDto}
     */
    CertificateDto,

    /**
     * The CertificatesVm model constructor.
     * @property {module:model/CertificatesVm}
     */
    CertificatesVm,

    /**
     * The Channel model constructor.
     * @property {module:model/Channel}
     */
    Channel,

    /**
     * The ChannelDto model constructor.
     * @property {module:model/ChannelDto}
     */
    ChannelDto,

    /**
     * The ChannelRevisionSelectionStrategy model constructor.
     * @property {module:model/ChannelRevisionSelectionStrategy}
     */
    ChannelRevisionSelectionStrategy,

    /**
     * The ChannelsVm model constructor.
     * @property {module:model/ChannelsVm}
     */
    ChannelsVm,

    /**
     * The CreateAccountCommand model constructor.
     * @property {module:model/CreateAccountCommand}
     */
    CreateAccountCommand,

    /**
     * The CreateAppCommand model constructor.
     * @property {module:model/CreateAppCommand}
     */
    CreateAppCommand,

    /**
     * The CreateCertificateCommand model constructor.
     * @property {module:model/CreateCertificateCommand}
     */
    CreateCertificateCommand,

    /**
     * The CreateChannelCommand model constructor.
     * @property {module:model/CreateChannelCommand}
     */
    CreateChannelCommand,

    /**
     * The CreateEnvironmentVariableCommand model constructor.
     * @property {module:model/CreateEnvironmentVariableCommand}
     */
    CreateEnvironmentVariableCommand,

    /**
     * The CreateTokenCommand model constructor.
     * @property {module:model/CreateTokenCommand}
     */
    CreateTokenCommand,

    /**
     * The DomainEvent model constructor.
     * @property {module:model/DomainEvent}
     */
    DomainEvent,

    /**
     * The EnvironmentVariable model constructor.
     * @property {module:model/EnvironmentVariable}
     */
    EnvironmentVariable,

    /**
     * The EnvironmentVariableDto model constructor.
     * @property {module:model/EnvironmentVariableDto}
     */
    EnvironmentVariableDto,

    /**
     * The EnvironmentVariablesVm model constructor.
     * @property {module:model/EnvironmentVariablesVm}
     */
    EnvironmentVariablesVm,

    /**
     * The RegisterRevisionCommand model constructor.
     * @property {module:model/RegisterRevisionCommand}
     */
    RegisterRevisionCommand,

    /**
     * The Revision model constructor.
     * @property {module:model/Revision}
     */
    Revision,

    /**
     * The RevisionDto model constructor.
     * @property {module:model/RevisionDto}
     */
    RevisionDto,

    /**
     * The RevisionsVm model constructor.
     * @property {module:model/RevisionsVm}
     */
    RevisionsVm,

    /**
     * The TokenInfo model constructor.
     * @property {module:model/TokenInfo}
     */
    TokenInfo,

    /**
    * The AccountApi service constructor.
    * @property {module:api/AccountApi}
    */
    AccountApi,

    /**
    * The AppApi service constructor.
    * @property {module:api/AppApi}
    */
    AppApi,

    /**
    * The CertificateApi service constructor.
    * @property {module:api/CertificateApi}
    */
    CertificateApi,

    /**
    * The ChannelApi service constructor.
    * @property {module:api/ChannelApi}
    */
    ChannelApi,

    /**
    * The EnvironmentVariableApi service constructor.
    * @property {module:api/EnvironmentVariableApi}
    */
    EnvironmentVariableApi,

    /**
    * The RevisionApi service constructor.
    * @property {module:api/RevisionApi}
    */
    RevisionApi
};
