/*
 * Hippo.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppItem {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "storageId")]
    pub storage_id: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "channels")]
    pub channels: Vec<crate::models::AppChannelListItem>,
}

impl AppItem {
    pub fn new(id: uuid::Uuid, name: String, storage_id: String, channels: Vec<crate::models::AppChannelListItem>) -> AppItem {
        AppItem {
            id,
            name,
            storage_id,
            description: None,
            channels,
        }
    }
}


