/*
 * Hippo.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicationChannelSummary {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "activeRevisionNumber", skip_serializing_if = "Option::is_none")]
    pub active_revision_number: Option<String>,
}

impl ApplicationChannelSummary {
    pub fn new(id: String, name: String) -> ApplicationChannelSummary {
        ApplicationChannelSummary {
            id,
            name,
            active_revision_number: None,
        }
    }
}


