/*
 * Hippo.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppsVm {
    #[serde(rename = "apps")]
    pub apps: Vec<crate::models::AppDto>,
}

impl AppsVm {
    pub fn new(apps: Vec<crate::models::AppDto>) -> AppsVm {
        AppsVm {
            apps,
        }
    }
}


