/*
 * Hippo.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChannelRevisionSelectionStrategy {
    #[serde(rename = "UseRangeRule")]
    UseRangeRule,
    #[serde(rename = "UseSpecifiedRevision")]
    UseSpecifiedRevision,

}

impl ToString for ChannelRevisionSelectionStrategy {
    fn to_string(&self) -> String {
        match self {
            Self::UseRangeRule => String::from("UseRangeRule"),
            Self::UseSpecifiedRevision => String::from("UseSpecifiedRevision"),
        }
    }
}

impl Default for ChannelRevisionSelectionStrategy {
    fn default() -> ChannelRevisionSelectionStrategy {
        Self::UseRangeRule
    }
}




