/*
 * Hippo.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChannelSummaryDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "appSummary")]
    pub app_summary: Box<crate::models::AppSummaryDto>,
}

impl ChannelSummaryDto {
    pub fn new(id: String, name: String, domain: String, app_summary: crate::models::AppSummaryDto) -> ChannelSummaryDto {
        ChannelSummaryDto {
            id,
            name,
            domain,
            app_summary: Box::new(app_summary),
        }
    }
}


