/*
 * Hippo.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateAccountCommand {
    #[serde(rename = "userName", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "passwordConfirm", skip_serializing_if = "Option::is_none")]
    pub password_confirm: Option<String>,
}

impl CreateAccountCommand {
    pub fn new() -> CreateAccountCommand {
        CreateAccountCommand {
            user_name: None,
            password: None,
            password_confirm: None,
        }
    }
}


