/*
 * Hippo.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GuidNullableField {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<uuid::Uuid>,
}

impl GuidNullableField {
    pub fn new() -> GuidNullableField {
        GuidNullableField {
            value: None,
        }
    }
}


