/*
 * Hippo.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateCertificateCommand {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "publicKey")]
    pub public_key: String,
    #[serde(rename = "privateKey")]
    pub private_key: String,
}

impl UpdateCertificateCommand {
    pub fn new(id: uuid::Uuid, name: String, public_key: String, private_key: String) -> UpdateCertificateCommand {
        UpdateCertificateCommand {
            id,
            name,
            public_key,
            private_key,
        }
    }
}


