/*
 * Hippo.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateChannelCommand {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "revisionSelectionStrategy")]
    pub revision_selection_strategy: crate::models::ChannelRevisionSelectionStrategy,
    #[serde(rename = "rangeRule", skip_serializing_if = "Option::is_none")]
    pub range_rule: Option<String>,
    #[serde(rename = "activeRevisionId", skip_serializing_if = "Option::is_none")]
    pub active_revision_id: Option<String>,
    #[serde(rename = "certificateId", skip_serializing_if = "Option::is_none")]
    pub certificate_id: Option<String>,
}

impl UpdateChannelCommand {
    pub fn new(id: String, name: String, domain: String, revision_selection_strategy: crate::models::ChannelRevisionSelectionStrategy) -> UpdateChannelCommand {
        UpdateChannelCommand {
            id,
            name,
            domain,
            revision_selection_strategy,
            range_rule: None,
            active_revision_id: None,
            certificate_id: None,
        }
    }
}


