/*
Hippo.Web

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hippo-openapi

import (
	"encoding/json"
)

// EnvironmentVariableDto struct for EnvironmentVariableDto
type EnvironmentVariableDto struct {
	Id string `json:"id"`
	ChannelId string `json:"channelId"`
	Key string `json:"key"`
	Value string `json:"value"`
}

// NewEnvironmentVariableDto instantiates a new EnvironmentVariableDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentVariableDto(id string, channelId string, key string, value string) *EnvironmentVariableDto {
	this := EnvironmentVariableDto{}
	this.Id = id
	this.ChannelId = channelId
	this.Key = key
	this.Value = value
	return &this
}

// NewEnvironmentVariableDtoWithDefaults instantiates a new EnvironmentVariableDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentVariableDtoWithDefaults() *EnvironmentVariableDto {
	this := EnvironmentVariableDto{}
	return &this
}

// GetId returns the Id field value
func (o *EnvironmentVariableDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EnvironmentVariableDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EnvironmentVariableDto) SetId(v string) {
	o.Id = v
}

// GetChannelId returns the ChannelId field value
func (o *EnvironmentVariableDto) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *EnvironmentVariableDto) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *EnvironmentVariableDto) SetChannelId(v string) {
	o.ChannelId = v
}

// GetKey returns the Key field value
func (o *EnvironmentVariableDto) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *EnvironmentVariableDto) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *EnvironmentVariableDto) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *EnvironmentVariableDto) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *EnvironmentVariableDto) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *EnvironmentVariableDto) SetValue(v string) {
	o.Value = v
}

func (o EnvironmentVariableDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["channelId"] = o.ChannelId
	}
	if true {
		toSerialize["key"] = o.Key
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableEnvironmentVariableDto struct {
	value *EnvironmentVariableDto
	isSet bool
}

func (v NullableEnvironmentVariableDto) Get() *EnvironmentVariableDto {
	return v.value
}

func (v *NullableEnvironmentVariableDto) Set(val *EnvironmentVariableDto) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentVariableDto) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentVariableDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentVariableDto(val *EnvironmentVariableDto) *NullableEnvironmentVariableDto {
	return &NullableEnvironmentVariableDto{value: val, isSet: true}
}

func (v NullableEnvironmentVariableDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentVariableDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


