/*
Hippo.Web

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hippo-openapi

import (
	"encoding/json"
)

// AppChannelListItem struct for AppChannelListItem
type AppChannelListItem struct {
	Id string `json:"id"`
	Name string `json:"name"`
	ActiveRevisionNumber NullableString `json:"activeRevisionNumber,omitempty"`
}

// NewAppChannelListItem instantiates a new AppChannelListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppChannelListItem(id string, name string) *AppChannelListItem {
	this := AppChannelListItem{}
	this.Id = id
	this.Name = name
	return &this
}

// NewAppChannelListItemWithDefaults instantiates a new AppChannelListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppChannelListItemWithDefaults() *AppChannelListItem {
	this := AppChannelListItem{}
	return &this
}

// GetId returns the Id field value
func (o *AppChannelListItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AppChannelListItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AppChannelListItem) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *AppChannelListItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AppChannelListItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AppChannelListItem) SetName(v string) {
	o.Name = v
}

// GetActiveRevisionNumber returns the ActiveRevisionNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppChannelListItem) GetActiveRevisionNumber() string {
	if o == nil || o.ActiveRevisionNumber.Get() == nil {
		var ret string
		return ret
	}
	return *o.ActiveRevisionNumber.Get()
}

// GetActiveRevisionNumberOk returns a tuple with the ActiveRevisionNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppChannelListItem) GetActiveRevisionNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActiveRevisionNumber.Get(), o.ActiveRevisionNumber.IsSet()
}

// HasActiveRevisionNumber returns a boolean if a field has been set.
func (o *AppChannelListItem) HasActiveRevisionNumber() bool {
	if o != nil && o.ActiveRevisionNumber.IsSet() {
		return true
	}

	return false
}

// SetActiveRevisionNumber gets a reference to the given NullableString and assigns it to the ActiveRevisionNumber field.
func (o *AppChannelListItem) SetActiveRevisionNumber(v string) {
	o.ActiveRevisionNumber.Set(&v)
}
// SetActiveRevisionNumberNil sets the value for ActiveRevisionNumber to be an explicit nil
func (o *AppChannelListItem) SetActiveRevisionNumberNil() {
	o.ActiveRevisionNumber.Set(nil)
}

// UnsetActiveRevisionNumber ensures that no value is present for ActiveRevisionNumber, not even an explicit nil
func (o *AppChannelListItem) UnsetActiveRevisionNumber() {
	o.ActiveRevisionNumber.Unset()
}

func (o AppChannelListItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.ActiveRevisionNumber.IsSet() {
		toSerialize["activeRevisionNumber"] = o.ActiveRevisionNumber.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableAppChannelListItem struct {
	value *AppChannelListItem
	isSet bool
}

func (v NullableAppChannelListItem) Get() *AppChannelListItem {
	return v.value
}

func (v *NullableAppChannelListItem) Set(val *AppChannelListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableAppChannelListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableAppChannelListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppChannelListItem(val *AppChannelListItem) *NullableAppChannelListItem {
	return &NullableAppChannelListItem{value: val, isSet: true}
}

func (v NullableAppChannelListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppChannelListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


