/*
Hippo.Web

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hippo-openapi

import (
	"encoding/json"
)

// CreateAppCommand struct for CreateAppCommand
type CreateAppCommand struct {
	Name NullableString `json:"name,omitempty"`
	StorageId NullableString `json:"storageId,omitempty"`
}

// NewCreateAppCommand instantiates a new CreateAppCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAppCommand() *CreateAppCommand {
	this := CreateAppCommand{}
	return &this
}

// NewCreateAppCommandWithDefaults instantiates a new CreateAppCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAppCommandWithDefaults() *CreateAppCommand {
	this := CreateAppCommand{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAppCommand) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAppCommand) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *CreateAppCommand) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *CreateAppCommand) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *CreateAppCommand) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *CreateAppCommand) UnsetName() {
	o.Name.Unset()
}

// GetStorageId returns the StorageId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAppCommand) GetStorageId() string {
	if o == nil || o.StorageId.Get() == nil {
		var ret string
		return ret
	}
	return *o.StorageId.Get()
}

// GetStorageIdOk returns a tuple with the StorageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAppCommand) GetStorageIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.StorageId.Get(), o.StorageId.IsSet()
}

// HasStorageId returns a boolean if a field has been set.
func (o *CreateAppCommand) HasStorageId() bool {
	if o != nil && o.StorageId.IsSet() {
		return true
	}

	return false
}

// SetStorageId gets a reference to the given NullableString and assigns it to the StorageId field.
func (o *CreateAppCommand) SetStorageId(v string) {
	o.StorageId.Set(&v)
}
// SetStorageIdNil sets the value for StorageId to be an explicit nil
func (o *CreateAppCommand) SetStorageIdNil() {
	o.StorageId.Set(nil)
}

// UnsetStorageId ensures that no value is present for StorageId, not even an explicit nil
func (o *CreateAppCommand) UnsetStorageId() {
	o.StorageId.Unset()
}

func (o CreateAppCommand) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.StorageId.IsSet() {
		toSerialize["storageId"] = o.StorageId.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableCreateAppCommand struct {
	value *CreateAppCommand
	isSet bool
}

func (v NullableCreateAppCommand) Get() *CreateAppCommand {
	return v.value
}

func (v *NullableCreateAppCommand) Set(val *CreateAppCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAppCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAppCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAppCommand(val *CreateAppCommand) *NullableCreateAppCommand {
	return &NullableCreateAppCommand{value: val, isSet: true}
}

func (v NullableCreateAppCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAppCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


