/*
Hippo.Web

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hippo-openapi

import (
	"encoding/json"
)

// CertificateDto struct for CertificateDto
type CertificateDto struct {
	Id string `json:"id"`
	Name string `json:"name"`
	PublicKey string `json:"publicKey"`
	PrivateKey string `json:"privateKey"`
	Channels []ChannelDto `json:"channels"`
}

// NewCertificateDto instantiates a new CertificateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateDto(id string, name string, publicKey string, privateKey string, channels []ChannelDto) *CertificateDto {
	this := CertificateDto{}
	this.Id = id
	this.Name = name
	this.PublicKey = publicKey
	this.PrivateKey = privateKey
	this.Channels = channels
	return &this
}

// NewCertificateDtoWithDefaults instantiates a new CertificateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateDtoWithDefaults() *CertificateDto {
	this := CertificateDto{}
	return &this
}

// GetId returns the Id field value
func (o *CertificateDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CertificateDto) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CertificateDto) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CertificateDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CertificateDto) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CertificateDto) SetName(v string) {
	o.Name = v
}

// GetPublicKey returns the PublicKey field value
func (o *CertificateDto) GetPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value
// and a boolean to check if the value has been set.
func (o *CertificateDto) GetPublicKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PublicKey, true
}

// SetPublicKey sets field value
func (o *CertificateDto) SetPublicKey(v string) {
	o.PublicKey = v
}

// GetPrivateKey returns the PrivateKey field value
func (o *CertificateDto) GetPrivateKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrivateKey
}

// GetPrivateKeyOk returns a tuple with the PrivateKey field value
// and a boolean to check if the value has been set.
func (o *CertificateDto) GetPrivateKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PrivateKey, true
}

// SetPrivateKey sets field value
func (o *CertificateDto) SetPrivateKey(v string) {
	o.PrivateKey = v
}

// GetChannels returns the Channels field value
func (o *CertificateDto) GetChannels() []ChannelDto {
	if o == nil {
		var ret []ChannelDto
		return ret
	}

	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value
// and a boolean to check if the value has been set.
func (o *CertificateDto) GetChannelsOk() (*[]ChannelDto, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Channels, true
}

// SetChannels sets field value
func (o *CertificateDto) SetChannels(v []ChannelDto) {
	o.Channels = v
}

func (o CertificateDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["publicKey"] = o.PublicKey
	}
	if true {
		toSerialize["privateKey"] = o.PrivateKey
	}
	if true {
		toSerialize["channels"] = o.Channels
	}
	return json.Marshal(toSerialize)
}

type NullableCertificateDto struct {
	value *CertificateDto
	isSet bool
}

func (v NullableCertificateDto) Get() *CertificateDto {
	return v.value
}

func (v *NullableCertificateDto) Set(val *CertificateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateDto(val *CertificateDto) *NullableCertificateDto {
	return &NullableCertificateDto{value: val, isSet: true}
}

func (v NullableCertificateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


