/*
Hippo.Web

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hippo-openapi

import (
	"encoding/json"
)

// ChannelDetailsDto struct for ChannelDetailsDto
type ChannelDetailsDto struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Domain string `json:"domain"`
	RevisionSelectionStrategy ChannelRevisionSelectionStrategy `json:"revisionSelectionStrategy"`
	ActiveRevision *RevisionDetailsDto `json:"activeRevision,omitempty"`
	RangeRule NullableString `json:"rangeRule,omitempty"`
	Certificate *Certificate `json:"certificate,omitempty"`
	EnvironmentVariables []EnvironmentVariableDto `json:"environmentVariables"`
}

// NewChannelDetailsDto instantiates a new ChannelDetailsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelDetailsDto(id string, name string, domain string, revisionSelectionStrategy ChannelRevisionSelectionStrategy, environmentVariables []EnvironmentVariableDto) *ChannelDetailsDto {
	this := ChannelDetailsDto{}
	this.Id = id
	this.Name = name
	this.Domain = domain
	this.RevisionSelectionStrategy = revisionSelectionStrategy
	this.EnvironmentVariables = environmentVariables
	return &this
}

// NewChannelDetailsDtoWithDefaults instantiates a new ChannelDetailsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelDetailsDtoWithDefaults() *ChannelDetailsDto {
	this := ChannelDetailsDto{}
	return &this
}

// GetId returns the Id field value
func (o *ChannelDetailsDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChannelDetailsDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChannelDetailsDto) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ChannelDetailsDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ChannelDetailsDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ChannelDetailsDto) SetName(v string) {
	o.Name = v
}

// GetDomain returns the Domain field value
func (o *ChannelDetailsDto) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *ChannelDetailsDto) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *ChannelDetailsDto) SetDomain(v string) {
	o.Domain = v
}

// GetRevisionSelectionStrategy returns the RevisionSelectionStrategy field value
func (o *ChannelDetailsDto) GetRevisionSelectionStrategy() ChannelRevisionSelectionStrategy {
	if o == nil {
		var ret ChannelRevisionSelectionStrategy
		return ret
	}

	return o.RevisionSelectionStrategy
}

// GetRevisionSelectionStrategyOk returns a tuple with the RevisionSelectionStrategy field value
// and a boolean to check if the value has been set.
func (o *ChannelDetailsDto) GetRevisionSelectionStrategyOk() (*ChannelRevisionSelectionStrategy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RevisionSelectionStrategy, true
}

// SetRevisionSelectionStrategy sets field value
func (o *ChannelDetailsDto) SetRevisionSelectionStrategy(v ChannelRevisionSelectionStrategy) {
	o.RevisionSelectionStrategy = v
}

// GetActiveRevision returns the ActiveRevision field value if set, zero value otherwise.
func (o *ChannelDetailsDto) GetActiveRevision() RevisionDetailsDto {
	if o == nil || o.ActiveRevision == nil {
		var ret RevisionDetailsDto
		return ret
	}
	return *o.ActiveRevision
}

// GetActiveRevisionOk returns a tuple with the ActiveRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelDetailsDto) GetActiveRevisionOk() (*RevisionDetailsDto, bool) {
	if o == nil || o.ActiveRevision == nil {
		return nil, false
	}
	return o.ActiveRevision, true
}

// HasActiveRevision returns a boolean if a field has been set.
func (o *ChannelDetailsDto) HasActiveRevision() bool {
	if o != nil && o.ActiveRevision != nil {
		return true
	}

	return false
}

// SetActiveRevision gets a reference to the given RevisionDetailsDto and assigns it to the ActiveRevision field.
func (o *ChannelDetailsDto) SetActiveRevision(v RevisionDetailsDto) {
	o.ActiveRevision = &v
}

// GetRangeRule returns the RangeRule field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChannelDetailsDto) GetRangeRule() string {
	if o == nil || o.RangeRule.Get() == nil {
		var ret string
		return ret
	}
	return *o.RangeRule.Get()
}

// GetRangeRuleOk returns a tuple with the RangeRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChannelDetailsDto) GetRangeRuleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RangeRule.Get(), o.RangeRule.IsSet()
}

// HasRangeRule returns a boolean if a field has been set.
func (o *ChannelDetailsDto) HasRangeRule() bool {
	if o != nil && o.RangeRule.IsSet() {
		return true
	}

	return false
}

// SetRangeRule gets a reference to the given NullableString and assigns it to the RangeRule field.
func (o *ChannelDetailsDto) SetRangeRule(v string) {
	o.RangeRule.Set(&v)
}
// SetRangeRuleNil sets the value for RangeRule to be an explicit nil
func (o *ChannelDetailsDto) SetRangeRuleNil() {
	o.RangeRule.Set(nil)
}

// UnsetRangeRule ensures that no value is present for RangeRule, not even an explicit nil
func (o *ChannelDetailsDto) UnsetRangeRule() {
	o.RangeRule.Unset()
}

// GetCertificate returns the Certificate field value if set, zero value otherwise.
func (o *ChannelDetailsDto) GetCertificate() Certificate {
	if o == nil || o.Certificate == nil {
		var ret Certificate
		return ret
	}
	return *o.Certificate
}

// GetCertificateOk returns a tuple with the Certificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelDetailsDto) GetCertificateOk() (*Certificate, bool) {
	if o == nil || o.Certificate == nil {
		return nil, false
	}
	return o.Certificate, true
}

// HasCertificate returns a boolean if a field has been set.
func (o *ChannelDetailsDto) HasCertificate() bool {
	if o != nil && o.Certificate != nil {
		return true
	}

	return false
}

// SetCertificate gets a reference to the given Certificate and assigns it to the Certificate field.
func (o *ChannelDetailsDto) SetCertificate(v Certificate) {
	o.Certificate = &v
}

// GetEnvironmentVariables returns the EnvironmentVariables field value
func (o *ChannelDetailsDto) GetEnvironmentVariables() []EnvironmentVariableDto {
	if o == nil {
		var ret []EnvironmentVariableDto
		return ret
	}

	return o.EnvironmentVariables
}

// GetEnvironmentVariablesOk returns a tuple with the EnvironmentVariables field value
// and a boolean to check if the value has been set.
func (o *ChannelDetailsDto) GetEnvironmentVariablesOk() ([]EnvironmentVariableDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnvironmentVariables, true
}

// SetEnvironmentVariables sets field value
func (o *ChannelDetailsDto) SetEnvironmentVariables(v []EnvironmentVariableDto) {
	o.EnvironmentVariables = v
}

func (o ChannelDetailsDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["domain"] = o.Domain
	}
	if true {
		toSerialize["revisionSelectionStrategy"] = o.RevisionSelectionStrategy
	}
	if o.ActiveRevision != nil {
		toSerialize["activeRevision"] = o.ActiveRevision
	}
	if o.RangeRule.IsSet() {
		toSerialize["rangeRule"] = o.RangeRule.Get()
	}
	if o.Certificate != nil {
		toSerialize["certificate"] = o.Certificate
	}
	if true {
		toSerialize["environmentVariables"] = o.EnvironmentVariables
	}
	return json.Marshal(toSerialize)
}

type NullableChannelDetailsDto struct {
	value *ChannelDetailsDto
	isSet bool
}

func (v NullableChannelDetailsDto) Get() *ChannelDetailsDto {
	return v.value
}

func (v *NullableChannelDetailsDto) Set(val *ChannelDetailsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelDetailsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelDetailsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelDetailsDto(val *ChannelDetailsDto) *NullableChannelDetailsDto {
	return &NullableChannelDetailsDto{value: val, isSet: true}
}

func (v NullableChannelDetailsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelDetailsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


