/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppItem from './AppItem';

/**
 * The AppItemPage model module.
 * @module model/AppItemPage
 * @version 1.0
 */
class AppItemPage {
    /**
     * Constructs a new <code>AppItemPage</code>.
     * @alias module:model/AppItemPage
     */
    constructor() { 
        
        AppItemPage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AppItemPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppItemPage} obj Optional instance to populate.
     * @return {module:model/AppItemPage} The populated <code>AppItemPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppItemPage();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [AppItem]);
            }
            if (data.hasOwnProperty('totalItems')) {
                obj['totalItems'] = ApiClient.convertToType(data['totalItems'], 'Number');
            }
            if (data.hasOwnProperty('pageIndex')) {
                obj['pageIndex'] = ApiClient.convertToType(data['pageIndex'], 'Number');
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
            }
            if (data.hasOwnProperty('isLastPage')) {
                obj['isLastPage'] = ApiClient.convertToType(data['isLastPage'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/AppItem>} items
 */
AppItemPage.prototype['items'] = undefined;

/**
 * @member {Number} totalItems
 */
AppItemPage.prototype['totalItems'] = undefined;

/**
 * @member {Number} pageIndex
 */
AppItemPage.prototype['pageIndex'] = undefined;

/**
 * @member {Number} pageSize
 */
AppItemPage.prototype['pageSize'] = undefined;

/**
 * @member {Boolean} isLastPage
 */
AppItemPage.prototype['isLastPage'] = undefined;






export default AppItemPage;

