/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApplicationChannelSummary model module.
 * @module model/ApplicationChannelSummary
 * @version 1.0
 */
class ApplicationChannelSummary {
    /**
     * Constructs a new <code>ApplicationChannelSummary</code>.
     * @alias module:model/ApplicationChannelSummary
     * @param id {String} 
     * @param name {String} 
     */
    constructor(id, name) { 
        
        ApplicationChannelSummary.initialize(this, id, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name) { 
        obj['id'] = id;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ApplicationChannelSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationChannelSummary} obj Optional instance to populate.
     * @return {module:model/ApplicationChannelSummary} The populated <code>ApplicationChannelSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationChannelSummary();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('activeRevisionNumber')) {
                obj['activeRevisionNumber'] = ApiClient.convertToType(data['activeRevisionNumber'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ApplicationChannelSummary.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ApplicationChannelSummary.prototype['name'] = undefined;

/**
 * @member {String} activeRevisionNumber
 */
ApplicationChannelSummary.prototype['activeRevisionNumber'] = undefined;






export default ApplicationChannelSummary;

