/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppDto from './AppDto';

/**
 * The AppsVm model module.
 * @module model/AppsVm
 * @version 1.0
 */
class AppsVm {
    /**
     * Constructs a new <code>AppsVm</code>.
     * @alias module:model/AppsVm
     */
    constructor() { 
        
        AppsVm.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AppsVm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppsVm} obj Optional instance to populate.
     * @return {module:model/AppsVm} The populated <code>AppsVm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppsVm();

            if (data.hasOwnProperty('apps')) {
                obj['apps'] = ApiClient.convertToType(data['apps'], [AppDto]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/AppDto>} apps
 */
AppsVm.prototype['apps'] = undefined;






export default AppsVm;

