/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChannelRevisionSelectionStrategy from './ChannelRevisionSelectionStrategy';

/**
 * The ChannelRevisionSelectionStrategyField model module.
 * @module model/ChannelRevisionSelectionStrategyField
 * @version 1.0
 */
class ChannelRevisionSelectionStrategyField {
    /**
     * Constructs a new <code>ChannelRevisionSelectionStrategyField</code>.
     * @alias module:model/ChannelRevisionSelectionStrategyField
     */
    constructor() { 
        
        ChannelRevisionSelectionStrategyField.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChannelRevisionSelectionStrategyField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChannelRevisionSelectionStrategyField} obj Optional instance to populate.
     * @return {module:model/ChannelRevisionSelectionStrategyField} The populated <code>ChannelRevisionSelectionStrategyField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelRevisionSelectionStrategyField();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ChannelRevisionSelectionStrategy.constructFromObject(data['value']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ChannelRevisionSelectionStrategy} value
 */
ChannelRevisionSelectionStrategyField.prototype['value'] = undefined;






export default ChannelRevisionSelectionStrategyField;

