/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Certificate from './Certificate';
import ChannelRevisionSelectionStrategy from './ChannelRevisionSelectionStrategy';
import Revision from './Revision';

/**
 * The CreateChannelCommand model module.
 * @module model/CreateChannelCommand
 * @version 1.0
 */
class CreateChannelCommand {
    /**
     * Constructs a new <code>CreateChannelCommand</code>.
     * @alias module:model/CreateChannelCommand
     */
    constructor() { 
        
        CreateChannelCommand.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateChannelCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateChannelCommand} obj Optional instance to populate.
     * @return {module:model/CreateChannelCommand} The populated <code>CreateChannelCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateChannelCommand();

            if (data.hasOwnProperty('appId')) {
                obj['appId'] = ApiClient.convertToType(data['appId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('revisionSelectionStrategy')) {
                obj['revisionSelectionStrategy'] = ChannelRevisionSelectionStrategy.constructFromObject(data['revisionSelectionStrategy']);
            }
            if (data.hasOwnProperty('rangeRule')) {
                obj['rangeRule'] = ApiClient.convertToType(data['rangeRule'], 'String');
            }
            if (data.hasOwnProperty('activeRevision')) {
                obj['activeRevision'] = Revision.constructFromObject(data['activeRevision']);
            }
            if (data.hasOwnProperty('certificate')) {
                obj['certificate'] = Certificate.constructFromObject(data['certificate']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} appId
 */
CreateChannelCommand.prototype['appId'] = undefined;

/**
 * @member {String} name
 */
CreateChannelCommand.prototype['name'] = undefined;

/**
 * @member {String} domain
 */
CreateChannelCommand.prototype['domain'] = undefined;

/**
 * @member {module:model/ChannelRevisionSelectionStrategy} revisionSelectionStrategy
 */
CreateChannelCommand.prototype['revisionSelectionStrategy'] = undefined;

/**
 * @member {String} rangeRule
 */
CreateChannelCommand.prototype['rangeRule'] = undefined;

/**
 * @member {module:model/Revision} activeRevision
 */
CreateChannelCommand.prototype['activeRevision'] = undefined;

/**
 * @member {module:model/Certificate} certificate
 */
CreateChannelCommand.prototype['certificate'] = undefined;






export default CreateChannelCommand;

