/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DomainEvent model module.
 * @module model/DomainEvent
 * @version 1.0
 */
class DomainEvent {
    /**
     * Constructs a new <code>DomainEvent</code>.
     * @alias module:model/DomainEvent
     */
    constructor() { 
        
        DomainEvent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DomainEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DomainEvent} obj Optional instance to populate.
     * @return {module:model/DomainEvent} The populated <code>DomainEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DomainEvent();

            if (data.hasOwnProperty('isPublished')) {
                obj['isPublished'] = ApiClient.convertToType(data['isPublished'], 'Boolean');
            }
            if (data.hasOwnProperty('dateOccurred')) {
                obj['dateOccurred'] = ApiClient.convertToType(data['dateOccurred'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} isPublished
 */
DomainEvent.prototype['isPublished'] = undefined;

/**
 * @member {Date} dateOccurred
 */
DomainEvent.prototype['dateOccurred'] = undefined;






export default DomainEvent;

