/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdateEnvironmentVariableDto from './UpdateEnvironmentVariableDto';

/**
 * The UpdateChannelEnvironmentVariablesCommand model module.
 * @module model/UpdateChannelEnvironmentVariablesCommand
 * @version 1.0
 */
class UpdateChannelEnvironmentVariablesCommand {
    /**
     * Constructs a new <code>UpdateChannelEnvironmentVariablesCommand</code>.
     * @alias module:model/UpdateChannelEnvironmentVariablesCommand
     */
    constructor() { 
        
        UpdateChannelEnvironmentVariablesCommand.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateChannelEnvironmentVariablesCommand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateChannelEnvironmentVariablesCommand} obj Optional instance to populate.
     * @return {module:model/UpdateChannelEnvironmentVariablesCommand} The populated <code>UpdateChannelEnvironmentVariablesCommand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateChannelEnvironmentVariablesCommand();

            if (data.hasOwnProperty('channelId')) {
                obj['channelId'] = ApiClient.convertToType(data['channelId'], 'String');
            }
            if (data.hasOwnProperty('environmentVariables')) {
                obj['environmentVariables'] = ApiClient.convertToType(data['environmentVariables'], [UpdateEnvironmentVariableDto]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} channelId
 */
UpdateChannelEnvironmentVariablesCommand.prototype['channelId'] = undefined;

/**
 * @member {Array.<module:model/UpdateEnvironmentVariableDto>} environmentVariables
 */
UpdateChannelEnvironmentVariablesCommand.prototype['environmentVariables'] = undefined;






export default UpdateChannelEnvironmentVariablesCommand;

