/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdateEnvironmentVariableDto from './UpdateEnvironmentVariableDto';

/**
 * The UpdateEnvironmentVariableDtoListField model module.
 * @module model/UpdateEnvironmentVariableDtoListField
 * @version 1.0
 */
class UpdateEnvironmentVariableDtoListField {
    /**
     * Constructs a new <code>UpdateEnvironmentVariableDtoListField</code>.
     * @alias module:model/UpdateEnvironmentVariableDtoListField
     */
    constructor() { 
        
        UpdateEnvironmentVariableDtoListField.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateEnvironmentVariableDtoListField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateEnvironmentVariableDtoListField} obj Optional instance to populate.
     * @return {module:model/UpdateEnvironmentVariableDtoListField} The populated <code>UpdateEnvironmentVariableDtoListField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateEnvironmentVariableDtoListField();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], [UpdateEnvironmentVariableDto]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/UpdateEnvironmentVariableDto>} value
 */
UpdateEnvironmentVariableDtoListField.prototype['value'] = undefined;






export default UpdateEnvironmentVariableDtoListField;

